import uuid
from datetime import datetime, timezone

from sqlalchemy import Column, DateTime, ForeignKey, String, Text, create_engine
from sqlalchemy.orm import declarative_base, sessionmaker

Base = declarative_base()


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


def new_id() -> str:
    return str(uuid.uuid4())


class User(Base):
    __tablename__ = "users"

    id = Column(String, primary_key=True, default=new_id)
    name = Column(String, nullable=False)
    token_hash = Column(String, unique=True, nullable=False)
    created_at = Column(DateTime(timezone=True), default=utcnow)


class Item(Base):
    __tablename__ = "items"

    # Generated by the phone so retries of the same share are idempotent.
    id = Column(String, primary_key=True)
    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)

    content_url = Column(Text, nullable=True)
    content_text = Column(Text, nullable=True)
    source_app = Column(String, nullable=True)
    user_note = Column(Text, nullable=True)
    quick_tag = Column(String, nullable=True)
    shared_at = Column(DateTime(timezone=True), nullable=False)

    # pending -> processing -> routed | failed
    status = Column(String, nullable=False, default="pending", index=True)
    content_type = Column(String, nullable=True)
    agent_summary = Column(Text, nullable=True)
    error = Column(Text, nullable=True)

    created_at = Column(DateTime(timezone=True), default=utcnow)
    updated_at = Column(DateTime(timezone=True), default=utcnow, onupdate=utcnow)


def make_sessionmaker(database_url: str) -> sessionmaker:
    connect_args = {"check_same_thread": False} if database_url.startswith("sqlite") else {}
    engine = create_engine(database_url, connect_args=connect_args, pool_pre_ping=True)
    Base.metadata.create_all(engine)
    return sessionmaker(bind=engine, autoflush=False, expire_on_commit=False)
